name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# ========================== LINTER STAGE ======================================
jobs:
  dev-style-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Dev-Style-Check 
      run:  make -C dev cpplint

  test-style-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test-Style-Check
      run:  make -C tests cpplint

  hardware-tests-style-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Hardware-Test-Style-Check
      run:  python3 tools/hwlint.py --dir tests/hardware/

  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup-cppcheck
      run:  sh tools/github/linux/cppcheck-config.sh
    - name: Run-cppcheck
      run:  sh tools/github/linux/cppcheck.sh

# ========================== BUILD STAGE ======================================
  build-linux:
    runs-on: ubuntu-latest
    needs: [dev-style-checking, test-style-checking, static-analysis, hardware-tests-style-checking]
    steps:
    - uses: actions/checkout@v3
    - name: Configure Building
      run: sh tools/github/linux/configure.sh
    - name: Building For STM32f103 Target
      run: make -C dev build
    - name: Upload objects artifact
      uses: actions/upload-artifact@v4
      with:
        name: objects-artifact
        path: dev/.build/

  build-winodws:
    runs-on: windows-latest
    needs: [dev-style-checking, test-style-checking, static-analysis, hardware-tests-style-checking]
    steps:
    - uses: actions/checkout@v3
    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; `
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    - name: Install ARM GCC Toolchain
      run: choco install -y gcc-arm-embedded
    - name: Add ARM GCC to PATH
      run: |
        $Env:Path += ';C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin'
    - name: Building For STM32f103 Target
      run: make -C dev build
    - name: Upload objects artifact
      uses: actions/upload-artifact@v4
      with:
        name: objects-artifact
        path: dev/.build/

  build-hardware-tests-linux:
    runs-on: ubuntu-latest
    needs: [dev-style-checking, test-style-checking, static-analysis, hardware-tests-style-checking, build-linux]
    steps:
    - uses: actions/checkout@v3
    - name: Configure Building
      run: sh tools/github/linux/configure.sh
    - name: Download objects artifact
      uses: actions/download-artifact@v4 
      with:
        name: objects-artifact
        path: dev/.build/
    - name: Building hardware tests
      run: make -C ./dev build-hw

  build-hardware-tests-windows:
    runs-on: windows-latest
    needs: [dev-style-checking, test-style-checking, static-analysis, hardware-tests-style-checking, build-winodws]
    steps:
    - uses: actions/checkout@v3
    - name: Configure Building
      run: ./tools/github/windows/configure.ps1
    - name: Download objects artifact
      uses: actions/download-artifact@v4 
      with:
        name: objects-artifact
        path: dev/.build/
    - name: Building hardware tests
      run: make -C ./dev build-hw

  build-unitests-linux:
    runs-on: ubuntu-latest
    needs: [dev-style-checking, test-style-checking, hardware-tests-style-checking, static-analysis]
    steps:
    - uses: actions/checkout@v3
    - name: Configure gtest
      run: sh tools/github/linux/configure-gtest.sh
    - name: Building tests
      run: make -C tests build-unittests
    - name: Upload objects artifact
      uses: actions/upload-artifact@v4
      with:
        name: objects-artifact
        path: tests/unittests/

  build-unitests-windows:
    runs-on: windows-latest
    needs: [dev-style-checking, test-style-checking, hardware-tests-style-checking, static-analysis]
    steps:
    - uses: actions/checkout@v3
    - name: Configure gtest
      run: ./tools/github/windows/configure-gtest.ps1
    - name: Building tests
      run: make -C tests build-unittests
    - name: Upload objects artifact
      uses: actions/upload-artifact@v4
      with:
        name: objects-artifact
        path: tests/unittests/

# ========================== TEST STAGE ========================================
  test-linux:
    runs-on: ubuntu-latest
    needs: [dev-style-checking, test-style-checking, hardware-tests-style-checking, static-analysis, build-unitests-linux]
    steps:
    - name: Download artifact 
      uses: actions/download-artifact@v4 
      with:
        name: objects-artifact
        path: tests/unittests/
    - name: Running tests
      run: |
       chmod -R 777 ./tests/ 
       ./tests/unittests/unittests.elf --gtest_shuffle

  test-windows:
    runs-on: windows-latest
    needs: [dev-style-checking, test-style-checking, hardware-tests-style-checking, static-analysis, build-unitests-windows]
    steps:
    - name: Download artifact 
      uses: actions/download-artifact@v4 
      with:
        name: objects-artifact
        path: tests/unittests/
    - name: Running tests
      run: |
       chmod -R 777 ./tests/ 
       ./tests/unittests/unittests.elf --gtest_shuffle