name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dev-style-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Dev-Style-Check 
      run:  make -C dev   cpplint
  test-style-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test-Style-Check
      run:  make -C tests cpplint

  build:
    runs-on: ubuntu-latest
    needs: [dev-style-checking, test-style-checking]
    steps:
    - uses: actions/checkout@v3
    - name: Configure Building
      run: sh /home/runner/work/stm32f10xxx_cpp_interface/stm32f10xxx_cpp_interface/tools/github/configure.sh
    - name: Building For STM32f103 Target
      run: make build
    - name: Upload objects artifact
      uses: actions/upload-artifact@v2
      with:
        name: objects-artifact
        path: /home/runner/work/stm32f10xxx_cpp_interface/stm32f10xxx_cpp_interface/dev/.build/

  test:
    runs-on: ubuntu-latest
    needs: [dev-style-checking, test-style-checking]
    steps:
    - uses: actions/checkout@v3
    - name: Configure gtest
      run: sh /home/runner/work/stm32f10xxx_cpp_interface/stm32f10xxx_cpp_interface/tools/github/configure-test.sh
    - name: Building tests
      run: make build-unittests
    - name: Running tests
      run: make run-unittests