name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

stages:
  - stage: Lint
    runs-on: ubuntu-latest
  - displayName: Lint
  - jobs:
    - job: dev-style-checking
    - displayName: dev-style-checking
      steps:
        - uses: actions/checkout@v3
        - name: Dev-Style-Check 
          run:  make -C dev cpplint
    - job: test-style-checking
    - displayName: test-style-checking
      steps:
        - uses: actions/checkout@v3
        - name: Test-Style-Check
          run:  make -C tests cpplint
    - job: cpp-check
    - displayName: cpp-check
      steps:
      - uses: actions/checkout@v4
      - name: Static-Analysis
        run:  sh tools/github/cppcheck-config.sh
