name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dev-style-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Dev-Style-Check 
      run:  make -C dev cpplint
  test-style-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test-Style-Check
      run:  make -C tests cpplint
  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup-cppcheck
      run:  sh tools/github/cppcheck-config.sh
    - name: Run-cppcheck
      run:  sh tools/github/cppcheck.sh

  build:
    runs-on: ubuntu-latest
    needs: [dev-style-checking, test-style-checking, static-analysis]
    steps:
    - uses: actions/checkout@v3
    - name: Configure dev Building
      run: sh tools/github/configure.sh
    - name: Building For STM32f103 Target
      run: make -C dev build
    - name: Upload objects artifact
      uses: actions/upload-artifact@v4
      with:
        name: objects-artifact
        path: dev/.build/
    - name: Configure gtest
      run: sh tools/github/configure-test.sh
    - name: Building unit tests
      run: make -C tests build-unittests
    - name: Upload objects artifact
      uses: actions/upload-artifact@v4
      with:
        name: objects-artifact
        path: ./
    - name: Building hardware tests
      run: echo "TODO"

  test:
    runs-on: ubuntu-latest
    needs: [dev-style-checking, test-style-checking, static-analysis, build]
    steps:
    - uses: actions/checkout@v3
    - name: Running tests
      run: make -C tests run-unittests