name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  style-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Dev-Style-Check 
      run:  make -C dev   cpplint
    - name: Test-Style-Check 
      run:  make -C tests cpplint

  build:
    runs-on: ubuntu-latest
    needs: [style-checking]
    steps:
    - uses: actions/checkout@v3
    - name: Configure Building
      run: sh /home/runner/work/stm32f10xxx_cpp_interface/stm32f10xxx_cpp_interface/tools/github/configure.sh
    - name: DBG
      run: ls /opt/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2?rev=78196d3461ba4c9089a67b5f33edf82a/
    - name: Building For STM32f103 Target
      run: make build
    - name: Upload objects artifact
      uses: actions/upload-artifact@v2
      with:
        name: objects-artifact
        path: /home/runner/work/stm32f10xxx_cpp_interface/stm32f10xxx_cpp_interface/dev/.build/

