name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dev-style-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Dev-Style-Check 
      run:  make -C dev cpplint
  test-style-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test-Style-Check
      run:  make -C tests cpplint
  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup-cppcheck
      run:  sh tools/github/cppcheck-config.sh
    - name: Run-cppcheck
      run:  sh tools/github/cppcheck.sh

  build:
    runs-on: ubuntu-latest
    needs: [dev-style-checking, test-style-checking, static-analysis]
    steps:
    - uses: actions/checkout@v3
    - name: Configure Building
      run: sh tools/github/configure.sh
    - name: Building For STM32f103 Target
      run: make -C dev build
    - name: Upload objects artifact
      uses: actions/upload-artifact@v4
      with:
        name: objects-artifact
        path: dev/.build/
  build-unitests:
    runs-on: ubuntu-latest
    needs: [dev-style-checking, test-style-checking, static-analysis]
    steps:
    - uses: actions/checkout@v3
    - name: Configure gtest
      run: sh tools/github/configure-test.sh
    - name: Building tests
      run: make -C tests build-unittests
    - name: Upload objects artifact
      uses: actions/upload-artifact@v4
      with:
        name: objects-artifact
        path: /home/runner/work/stm32f10xxx_cpp_interface/stm32f10xxx_cpp_interface/tests/unittests/unittests.elf
  test:
    runs-on: ubuntu-latest
    needs: [dev-style-checking, test-style-checking, static-analysis, build]
    steps:
    - name: Download artifact 
      uses: actions/download-artifact@v4
      with:
        name: test-object-artifact
        path: /home/runner/work/stm32f10xxx_cpp_interface/stm32f10xxx_cpp_interface/tests/unittests/unittests.elf
    - name: Running tests
      run: ./tests/unittests/unittests.elf --gtest_shuffle